---
- hosts: host-01
  vars_files:
    - vars/main.yml
  roles:
    - role: leonidas.nvm
      nvm:
        user: vagrant
        version: v0.31.1
        node_version: 'v4.4.4'
    - role: geerlingguy.nginx
    - role: geerlingguy.mysql
    - role: geerlingguy.git
    - role: dirn.tmux
      tmux_install_tmuxp: true
