apps:
  - script: server.js
    name: frontend
    cwd: /home/vagrant/source/h-frontend/
    max_restarts: 5
    watch: true
    ignore_watch: 
      - "node_modules"
      - "logs"
    env:
      NODE_ENV: development
    log_date_format: "YYYY-MM-DD HH:mm:ss"
    error_file: /home/vagrant/source/h-frontend/logs/frontend.log
    out_file: /home/vagrant/source/h-frontend/logs/frontend.log
    merge_logs: true


  - script : index.js
    name: database
    cwd: /home/vagrant/source/h-database/
    max_restarts: 5
    watch: true
    ignore_watch: 
      - "node_modules"
      - "images"
      - "logs"
    env:
      NODE_ENV: development
    log_date_format: "YYYY-MM-DD HH:mm:ss"
    error_file: /home/vagrant/source/h-database/logs/database.log
    out_file: /home/vagrant/source/h-database/logs/database.log
    merge_logs: true


  - script: index.js
    name: auth
    cwd: /home/vagrant/source/h-auth/
    max_restarts: 5
    watch: true
    ignore_watch: 
      - "node_modules"
      - "images"
      - "logs"
    env:
      NODE_ENV: development
    log_date_format: "YYYY-MM-DD HH:ss"
    error_file: /home/vagrant/source/h-auth/logs/auth.log
    out_file: /home/vagrant/source/h-auth/logs/auth.log
    merge_logs: true