apps:
  - script: server.js
    name: frontend
    cwd: h-frontend/
    watch: true
    env:
      NODE_ENV: development
  - script : index.js
    name: database
    cwd: h-database/
    watch: true
    env:
      NODE_ENV: development
  - script: index.js
    name: auth
    cwd: h-auth/
    watch: true
    env:
      NODE_ENV: development